version: '3.8'

services:
  app:
    build:
      context: ./auth-service
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:roottedexample@31.207.74.78:3306/user-service
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network
  main:
    build:
      context: ./k8s
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: mysql://root:roottedexample@31.207.74.78:3306/main
    volumes:
      - ./k8s:/k8s
      - /k8s/node_modules
    command: npm run dev
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0  # Используем вашу версию
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt  # <-- только этот, убрать остальные с letsencrypt
      - /usr/lib/nginx/modules:/usr/lib/nginx/modules:ro
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - app
      - main
    networks:
      - app-network
networks:
  app-network:
    driver: bridge